
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module Risc_v(

	//////////// LED //////////
	LEDG,
	LEDR,

	//////////// KEY //////////
	KEY,

	//////////// SW //////////
	SW,

	//////////// SEG7 //////////
	HEX0,
	HEX1,
	HEX2,
	HEX3,
	HEX4,
	HEX5,
	HEX6,
	HEX7
);

//=======================================================
//  PARAMETER declarations
//=======================================================


//=======================================================
//  PORT declarations
//=======================================================

//////////// LED //////////
output		     [8:0]		LEDG;
output		    [17:0]		LEDR;

//////////// KEY //////////
input 		     [3:0]		KEY;

//////////// SW //////////
input 		    [17:0]		SW;

//////////// SEG7 //////////
output		     [6:0]		HEX0;
output		     [6:0]		HEX1;
output		     [6:0]		HEX2;
output		     [6:0]		HEX3;
output		     [6:0]		HEX4;
output		     [6:0]		HEX5;
output		     [6:0]		HEX6;
output		     [6:0]		HEX7;

//=======================================================
//  REG/WIRE declarations
//=======================================================
	
	wire [31:0] instrucao;
	wire [31:0][11:0] Memoria_entrada;
	wire [31:0][11:0]Registers_entrada;
	
	wire alu;
	wire mem;
	wire REG;
	wire control;
	wire line;
	wire [11:0] WriteMem;
	
	wire ALUScr;
	wire Branch;
	wire MemRead;
	wire MemtoReg;
	wire MemWrite;
	wire RegWrite;
	
	wire [4:0] rd;
	wire [4:0] rs1;
	wire [4:0] rs2;
	wire [11:0] sum;
	wire [1:0] ALUOp;
	wire [11:0] data1;
	wire [11:0] data2;
	wire [6:0] opcode;
	wire [11:0] linha;
	wire [3:0] ALUcontrol;
	wire [11:0] ALUresult;
	wire [11:0] Writedata;
	wire signed [11:0] ImmGen;
	wire [31:0][11:0] Memoria_saida;
	wire [31:0][11:0] Registers_saida;
	wire [7:0] max;

//=======================================================
//  Structural coding
//=======================================================

	instructions instru(
		.clock(~KEY[0]),
		.reset(~KEY[1]),
		.linha(linha),
		.max(max),
		.Registers(Registers_saida),
		.Memoria(Memoria_saida),

		.instrucao(instrucao)
	);
	
	PC comp (	
		.clock(~KEY[0]),
		.reset(~KEY[1]),
		.line(line),
		.sum(sum),
		.instrucao(instrucao), 
		
		.linha(linha),
		.rd(rd), 
		.rs1(rs1), 
		.rs2(rs2), 
		.opcode(opcode)
	);
	
	Control controle (
		.instrucao(instrucao),
		.opcode(opcode),
		.clock(~KEY[0]),

		.Branch(Branch),
		.MemRead(MemRead),
		.MemtoReg(MemtoReg),
		.ALUOp(ALUOp),
		.MemWrite(MemWrite),
		.ALUScr(ALUScr),
		.RegWrite(RegWrite),
		.ALUcontrol(ALUcontrol),
		.ImmGen(ImmGen),
		.control(control)	
	);
		
	Registradores registers(	
		.rd(rd),
		.rs1(rs1),
		.rs2(rs2),
		.reset(~KEY[1]),
		.RegWrite(RegWrite),
		.MemWrite(MemWrite),
		.MemRead(MemRead),
		.Branch(Branch),
		.Writedata(Writedata),
		.ALUScr(ALUScr),
		.ImmGen(ImmGen),
		.ALUresult(ALUresult),
		.control(control),
		.mem(mem),
		.Registers_entrada(Registers_entrada),
		
		.Registers_saida(Registers_saida),
		.data1(data1),
		.data2(data2),
		.REG(REG),
		.WriteMem(WriteMem)
	);
	
		
	ALU  operacao(	
		.data1(data1),
		.data2(data2),
		.ALUcontrol(ALUcontrol),
		.ImmGen(ImmGen),
		.REG(REG),
		.Branch(Branch),
		.linha(linha),
		
		.ALUresult(ALUresult),
		.sum(sum),
		.line(line),
		.alu(alu)	
	);
	
	Memory m(	
		.MemWrite(MemWrite),
		.MemRead(MemRead),
		.MemtoReg(MemtoReg),
		.alu(alu),
		.reset(~KEY[1]),
		.ALUresult(ALUresult),
		.Memoria_entrada(Memoria_entrada),
		.WriteMem(WriteMem),
			
		.Memoria_saida(Memoria_saida),
		.Writedata(Writedata),
		.mem(mem)
		
	);	
	
	SevenSegmentConverter ssc(
			  .number(linha),
			  .segments1(HEX7),
			  .segments2(HEX6)
	);

	SevenSegmentConverter2 ssc1(
			  .r(SW[0]),
			  .m(SW[1]),
			  .number1(Registers_saida),
			  .number2(Memoria_saida),
			  .segments1(HEX5),
			  .segments2(HEX4),
			  .display1(HEX3),
			  .display2(HEX2),
			  .display3(HEX1),
			  .display4(HEX0),
			  .led(LEDG[1:0])
	);
endmodule
